### ISSUE TITLE
Getting an error on build attempt

### ISSUE THREAD

**Issue by daniel-sphereo** [serverless-stack/serverless-stack#117] opened 2021-02-18 19:31 UTC
Hi, 

I'm getting the following error on build attempt:

=====================================================================
npm run build

> infra@0.1.0 build /Users/daniellevin/Work/mixi-backend/infra
> sst build

Preparing your SST app
Detected tsconfig.json
Transpiling source
Linting source
Running type checker
node_modules/@serverless-stack/resources/src/util/builder.ts:4:22 - error TS7016: Could not find a declaration file for module 'zip-local'. '/Users/daniellevin/Work/mixi-backend/infra/node_modules/zip-local/main.js' implicitly has an 'any' type.
  Try `npm install @types/zip-local` if it exists or add a new declaration (.d.ts) file containing `declare module 'zip-local';`

4 import zipLocal from "zip-local";
                       ~~~~~~~~~~~

=====================================================================

node version: v12.20.1
os: macOS Big Sur 11.1

Any help will be greatly appreciated.

**Comment by jayair** [comment] 2021-02-18 20:07
This is asking you to install the types for the `zip-local` module that you are using. I think doing that npm install like the error message should work. Can you give that a try?

**Comment by fwang** [comment] 2021-02-18 22:43
@daniel-sphereo This might be our issue. I'm going to take a look.

**Comment by daniel-sphereo** [comment] 2021-02-21 08:36
I think it is. I'm not using this package. It happens after the clean install of the framework. The issue is rather urgent for me. Can you please suggest a quick workaround?

**Comment by daniel-sphereo** [comment] 2021-02-21 09:07
It looks like setting  "noImplicitAny" to **false** does the trick. Not sure if it is harmful in any way to the rest of sst's operations. There were other modules with missing types - something I was able to resolve by means of running "npm install -D @types/module-name" command. I can do another clean install and produce a list of those if it helps.

**Comment by jayair** [comment] 2021-02-24 23:05
@daniel-sphereo I'm looking into this issue. But I can't reproduce it for a new TS install. Which version of SST were you using? And was it from a fresh install as well?

**Comment by jayair** [comment] 2021-03-15 23:48
@daniel-sphereo just checking if you are still having this issue.

**Comment by thdxr** [comment] 2021-08-13 21:30
Going to close this issue for now - @daniel-sphereo let us know if you want to reopen it

**Closed by thdxr** 2021-08-13 21:30 UTC
Labels: bug
