### ISSUE TITLE
Large responses get a 500 respose after timing out only in dev mode

### ISSUE THREAD

**Issue by ryanmalesic** [serverless-stack/serverless-stack#305] opened 2021-04-13 22:45 UTC
Title. if deployed to AWS, the response is returned okay. The dev logs in console show the response item in json-stringified format with no error. Cloudwatch logs show a timeout. Increasing the timeout does not help.

**Comment by fwang** [comment] 2021-04-13 22:50
Hi @ryanmalesic, can you quickly check two things:
1. in the console, how long is the response? (ie. char length)
2. when this happens again, open up `.build/sst.debug.log` and see if you see any error message near the bottom of the log.

SST uses websocket to send response back to the Lambda, I suspect it might be caused by response size exceeded the websocket payload size (~128KB).

**Comment by ryanmalesic** [comment] 2021-04-13 23:13
> SST uses websocket to send response back to the Lambda, I suspect it might be caused by response size exceeded the websocket payload size (~128KB).

Yeah it's about 700kb. any way around this?

**Comment by fwang** [comment] 2021-04-13 23:31
Yeah probably something along the line of splitting the response into parts and piecing it back together in Lambda.

I will try to put a fix in tonight.

**Comment by fwang** [comment] 2021-04-14 10:00
@ryanmalesic Fixed in [v0.10.11](https://github.com/serverless-stack/serverless-stack/releases/tag/v0.10.11).

Give it a try and let me know if it works!

**Closed by fwang** 2021-04-14 10:00 UTC
Labels: bug
