### ISSUE TITLE
TypeScript checking failing

### ISSUE THREAD

**Issue by revmischa** [serverless-stack/serverless-stack#8] opened 2020-10-09 17:46 UTC
I seem to be running into some difficulty trying to use TypeScript:

<img width="607" alt="Screen Shot 2020-10-09 at 8 42 14 PM" src="https://user-images.githubusercontent.com/245131/95614866-eab04400-0a6f-11eb-9d87-32a99c041f0f.png">

<img width="585" alt="Screen Shot 2020-10-09 at 8 42 31 PM" src="https://user-images.githubusercontent.com/245131/95614891-f4d24280-0a6f-11eb-80ca-23f78888cceb.png">

<img width="620" alt="Screen Shot 2020-10-09 at 8 43 40 PM" src="https://user-images.githubusercontent.com/245131/95614974-1f240000-0a70-11eb-8fac-c173340af889.png">

![image](https://user-images.githubusercontent.com/245131/95616189-13d1d400-0a72-11eb-8adf-8f325acdf898.png)

**Comment by jayair** [comment] 2020-10-15 18:20
This seems very much like an issue caused by:

https://github.com/serverless-stack/serverless-stack#known-issues

Can you post your `package.json` here?

**Comment by thdxr** [comment] 2021-08-13 21:38
Hey @revmischa is this still an issue for you? Closing this issue for now but happy to reopen if you want to discuss further

**Closed by thdxr** 2021-08-13 21:38 UTC
Labels: question
